#include "include.h"

void az() {
	SetConsoleTitleA("ahoajndhquodqauuoeauegaueaeuoaheiahuoehaeaoihqazoundoiqduoqbsgduazqhjduoqbhdhiquoqnujiodqb");
	printf("(1)CreeUnDox\n\n");
	std::string dox;
	std::cin >> dox;
	if (dox == "1")
	{
		system("cls");
		printf("Prenom : ");
		std::string pren;
		std::cin >> pren;
		Sleep(500);
		system("cls");
		printf("Nom : ");
		std::string nom;
		std::cin >> nom;
		Sleep(500);
		system("cls");
		printf("Age : ");
		std::string age;
		std::cin >> age;
		Sleep(500);
		system("cls");
		printf("Ville : ");
		std::string ville;
		std::cin >> ville;
		Sleep(500);
		system("cls");
		printf("Adresse : ");
		std::string adresse1;
		std::cin >> adresse1;
		Sleep(500);
		system("cls");
		printf("Numero : ");
		std::string num1;
		std::cin >> num1;
		Sleep(500);
		system("cls");
		printf("Tete(Que sous lien) : ");
		std::string tete1;
		std::cin >> tete1;
		Sleep(500);
		system("cls");
		printf("Pere prenom : ");
		std::string dprenom;
		std::cin >> dprenom;
		Sleep(500);
		system("cls");
		printf("Nom : ");
		std::string nomm;
		std::cin >> nomm;
		Sleep(500);
		system("cls");
		printf("Age : ");
		std::string agee;
		std::cin >> agee;
		Sleep(500);
		system("cls");
		printf("Ville : ");
		std::string villee;
		std::cin >> villee;
		Sleep(500);
		system("cls");
		printf("Adresse : ");
		std::string adresse2;
		std::cin >> adresse2;
		Sleep(500);
		system("cls");
		printf("Numero Pere : ");
		std::string num2;
		std::cin >> num2;
		Sleep(500);
		system("cls");
		printf("Tete Pere(Que sous lien) : ");
		std::string tete2;
		std::cin >> tete2;
		Sleep(500);
		system("cls");
		printf("Mere prenom : ");
		std::string mprenom;
		std::cin >> mprenom;
		Sleep(500);
		system("cls");
		printf("Nom : ");
		std::string nommere;
		std::cin >> nommere;
		Sleep(500);
		system("cls");
		printf("Age : ");
		std::string agemere;
		std::cin >> agemere;
		Sleep(500);
		system("cls");
		printf("Ville : ");
		std::string villemere;
		std::cin >> villemere;
		Sleep(500);
		system("cls");
		printf("Adresse : ");
		std::string adresse3;
		std::cin >> adresse3;
		Sleep(500);
		system("cls");
		printf("Numero Mere : ");
		std::string num3;
		std::cin >> num3;
		Sleep(500);
		system("cls");
		printf("Tete Mere(Que sous lien) : ");
		std::string tete3;
		std::cin >> tete3;
		Sleep(500);
		system("cls");
		printf("Votre Pseudo : ");
		std::string pseudo;
		std::cin >> pseudo;
		Sleep(500);
		system("cls");


		std::ofstream pfile;
		pfile.open("EZdox.txt");
		pfile << "------------Fils-----------------\n";
		pfile << "Prénom : " + pren + "\n";
		pfile << "Nom : " + nom + "\n";
		pfile << "Age : " + age + "\n";
		pfile << "Ville : " + ville + "\n";
		pfile << "Adresse : " + adresse1 + "\n";
		pfile << "Numéro : " + num1 + "\n";
		pfile << "Tete : " + tete1 + "\n";
		pfile << "------------Pere-----------------\n";
		pfile << "Prénom : " + dprenom + "\n";
		pfile << "Nom : " + nomm + "\n";
		pfile << "Age : " + agee + "\n";
		pfile << "Ville : " + villee + "\n";
		pfile << "Adresse : " + adresse2 + "\n";
		pfile << "Numéro : " + num2 + "\n";
		pfile << "Tete : " + tete2 + "\n";
		pfile << "------------Mere-----------------\n";
		pfile << "Prénom : " + mprenom + "\n";
		pfile << "Nom : " + nommere + "\n";
		pfile << "Age : " + agemere + "\n";
		pfile << "Ville : " + villemere + "\n";
		pfile << "Adresse : " + adresse3 + "\n";
		pfile << "Numéro : " + num3 + "\n";
		pfile << "Tete : " + tete3 + "\n";
		pfile << "DOX Crée par " + pseudo + "\n";
		printf("Dox cree !!!!");
		Sleep(2000);
		exit(3);
	}
}



int main() {
	az();
}
